/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as FacultyIndexRouteImport } from './routes/faculty/index'
import { Route as StudentRoutineRouteImport } from './routes/student/routine'
import { Route as StudentRoomsRouteImport } from './routes/student/rooms'
import { Route as StudentAnalyticsRouteImport } from './routes/student/analytics'
import { Route as FacultyRoutineRouteImport } from './routes/faculty/routine'
import { Route as FacultyManageRouteImport } from './routes/faculty/manage'
import { Route as FacultyLoginRouteImport } from './routes/faculty/login'
import { Route as FacultyBookRouteImport } from './routes/faculty/book'
import { Route as FacultyAnalyticsRouteImport } from './routes/faculty/analytics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyIndexRoute = FacultyIndexRouteImport.update({
  id: '/faculty/',
  path: '/faculty/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoutineRoute = StudentRoutineRouteImport.update({
  id: '/student/routine',
  path: '/student/routine',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoomsRoute = StudentRoomsRouteImport.update({
  id: '/student/rooms',
  path: '/student/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAnalyticsRoute = StudentAnalyticsRouteImport.update({
  id: '/student/analytics',
  path: '/student/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoutineRoute = FacultyRoutineRouteImport.update({
  id: '/faculty/routine',
  path: '/faculty/routine',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyManageRoute = FacultyManageRouteImport.update({
  id: '/faculty/manage',
  path: '/faculty/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyLoginRoute = FacultyLoginRouteImport.update({
  id: '/faculty/login',
  path: '/faculty/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyBookRoute = FacultyBookRouteImport.update({
  id: '/faculty/book',
  path: '/faculty/book',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyAnalyticsRoute = FacultyAnalyticsRouteImport.update({
  id: '/faculty/analytics',
  path: '/faculty/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faculty/analytics': typeof FacultyAnalyticsRoute
  '/faculty/book': typeof FacultyBookRoute
  '/faculty/login': typeof FacultyLoginRoute
  '/faculty/manage': typeof FacultyManageRoute
  '/faculty/routine': typeof FacultyRoutineRoute
  '/student/analytics': typeof StudentAnalyticsRoute
  '/student/rooms': typeof StudentRoomsRoute
  '/student/routine': typeof StudentRoutineRoute
  '/faculty/': typeof FacultyIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faculty/analytics': typeof FacultyAnalyticsRoute
  '/faculty/book': typeof FacultyBookRoute
  '/faculty/login': typeof FacultyLoginRoute
  '/faculty/manage': typeof FacultyManageRoute
  '/faculty/routine': typeof FacultyRoutineRoute
  '/student/analytics': typeof StudentAnalyticsRoute
  '/student/rooms': typeof StudentRoomsRoute
  '/student/routine': typeof StudentRoutineRoute
  '/faculty': typeof FacultyIndexRoute
  '/student': typeof StudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faculty/analytics': typeof FacultyAnalyticsRoute
  '/faculty/book': typeof FacultyBookRoute
  '/faculty/login': typeof FacultyLoginRoute
  '/faculty/manage': typeof FacultyManageRoute
  '/faculty/routine': typeof FacultyRoutineRoute
  '/student/analytics': typeof StudentAnalyticsRoute
  '/student/rooms': typeof StudentRoomsRoute
  '/student/routine': typeof StudentRoutineRoute
  '/faculty/': typeof FacultyIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faculty/analytics'
    | '/faculty/book'
    | '/faculty/login'
    | '/faculty/manage'
    | '/faculty/routine'
    | '/student/analytics'
    | '/student/rooms'
    | '/student/routine'
    | '/faculty/'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faculty/analytics'
    | '/faculty/book'
    | '/faculty/login'
    | '/faculty/manage'
    | '/faculty/routine'
    | '/student/analytics'
    | '/student/rooms'
    | '/student/routine'
    | '/faculty'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/faculty/analytics'
    | '/faculty/book'
    | '/faculty/login'
    | '/faculty/manage'
    | '/faculty/routine'
    | '/student/analytics'
    | '/student/rooms'
    | '/student/routine'
    | '/faculty/'
    | '/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FacultyAnalyticsRoute: typeof FacultyAnalyticsRoute
  FacultyBookRoute: typeof FacultyBookRoute
  FacultyLoginRoute: typeof FacultyLoginRoute
  FacultyManageRoute: typeof FacultyManageRoute
  FacultyRoutineRoute: typeof FacultyRoutineRoute
  StudentAnalyticsRoute: typeof StudentAnalyticsRoute
  StudentRoomsRoute: typeof StudentRoomsRoute
  StudentRoutineRoute: typeof StudentRoutineRoute
  FacultyIndexRoute: typeof FacultyIndexRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/': {
      id: '/faculty/'
      path: '/faculty'
      fullPath: '/faculty/'
      preLoaderRoute: typeof FacultyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/routine': {
      id: '/student/routine'
      path: '/student/routine'
      fullPath: '/student/routine'
      preLoaderRoute: typeof StudentRoutineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/rooms': {
      id: '/student/rooms'
      path: '/student/rooms'
      fullPath: '/student/rooms'
      preLoaderRoute: typeof StudentRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/analytics': {
      id: '/student/analytics'
      path: '/student/analytics'
      fullPath: '/student/analytics'
      preLoaderRoute: typeof StudentAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/routine': {
      id: '/faculty/routine'
      path: '/faculty/routine'
      fullPath: '/faculty/routine'
      preLoaderRoute: typeof FacultyRoutineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/manage': {
      id: '/faculty/manage'
      path: '/faculty/manage'
      fullPath: '/faculty/manage'
      preLoaderRoute: typeof FacultyManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/login': {
      id: '/faculty/login'
      path: '/faculty/login'
      fullPath: '/faculty/login'
      preLoaderRoute: typeof FacultyLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/book': {
      id: '/faculty/book'
      path: '/faculty/book'
      fullPath: '/faculty/book'
      preLoaderRoute: typeof FacultyBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/analytics': {
      id: '/faculty/analytics'
      path: '/faculty/analytics'
      fullPath: '/faculty/analytics'
      preLoaderRoute: typeof FacultyAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FacultyAnalyticsRoute: FacultyAnalyticsRoute,
  FacultyBookRoute: FacultyBookRoute,
  FacultyLoginRoute: FacultyLoginRoute,
  FacultyManageRoute: FacultyManageRoute,
  FacultyRoutineRoute: FacultyRoutineRoute,
  StudentAnalyticsRoute: StudentAnalyticsRoute,
  StudentRoomsRoute: StudentRoomsRoute,
  StudentRoutineRoute: StudentRoutineRoute,
  FacultyIndexRoute: FacultyIndexRoute,
  StudentIndexRoute: StudentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
